# Generated by Django 3.2 on 2021-05-10 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20210509_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total_price')),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_product', models.CharField(default='title', max_length=225, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('image_of_product', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('description_of_product', models.TextField(null=True, verbose_name='Descripwtion')),
                ('price_of_product', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('screen_diagonal', models.CharField(max_length=12, verbose_name='screen_diagonal')),
                ('screen_resolution', models.CharField(max_length=123, verbose_name='Resolution')),
                ('smart_technology_support', models.CharField(max_length=20, verbose_name='Smart_technologies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='price',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='title',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='price',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='title',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='video',
        ),
        migrations.AddField(
            model_name='laptop',
            name='description_of_product',
            field=models.TextField(null=True, verbose_name='Descripwtion'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='image_of_product',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='price_of_product',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(default='any', max_length=255, verbose_name='Resolution'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='title_of_product',
            field=models.CharField(default='title', max_length=225, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='description_of_product',
            field=models.TextField(null=True, verbose_name='Descripwtion'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image_of_product',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='price_of_product',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='title_of_product',
            field=models.CharField(default='title', max_length=225, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='videocard',
            field=models.CharField(max_length=255, null=True, verbose_name='Videocard'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name_of_category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='display_type',
            field=models.CharField(max_length=255, verbose_name='Display_type'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor_frequency',
            field=models.CharField(max_length=255, verbose_name='Frequency_of_core '),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(max_length=12, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='time_without_charge',
            field=models.CharField(max_length=12, verbose_name='Time_of_acc_work'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='video',
            field=models.CharField(max_length=32, verbose_name='Videocard'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='accumulator_volume',
            field=models.CharField(max_length=235, verbose_name='Volume of acc'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='back_camera_mp',
            field=models.CharField(max_length=255, verbose_name='Back_camera'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_type',
            field=models.CharField(max_length=225, verbose_name='Display_type'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='front_camera_mp',
            field=models.CharField(max_length=255, verbose_name='Front_camera'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='random_access_memory',
            field=models.CharField(max_length=255, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='resolution',
            field=models.CharField(max_length=215, verbose_name='Resolution'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.AddField(
            model_name='television',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='basketitems',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='basketitems',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='shop.Basket'),
        ),
        migrations.AddField(
            model_name='basket',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='shop.basketitems', verbose_name='BasketItems'),
        ),
        migrations.AddField(
            model_name='basket',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Customer'),
        ),
    ]
