# Generated by Django 3.2 on 2021-05-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_smartphone_display_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='processor_frequency',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='time_without_charge',
        ),
        migrations.AddField(
            model_name='laptop',
            name='Product_create_company',
            field=models.CharField(max_length=12, null=True, verbose_name='Which_company_produce(Hp,lenovo e.t.c)'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=255, null=True, verbose_name='Core_model'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Product_create_company',
            field=models.CharField(max_length=12, null=True, verbose_name='Which_company_produce(Hp,lenovo e.t.c)'),
        ),
        migrations.AddField(
            model_name='television',
            name='company_produces',
            field=models.CharField(max_length=25, null=True, verbose_name='Which_company_produce(Hp,lenovo e.t.c)'),
        ),
    ]
