# Generated by Django 3.2 on 2021-05-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210510_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='title_of_product',
            field=models.CharField(max_length=225, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='title_of_product',
            field=models.CharField(max_length=225, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='television',
            name='title_of_product',
            field=models.CharField(max_length=225, null=True, verbose_name='Title'),
        ),
    ]
