# Generated by Django 3.2 on 2021-05-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210510_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_product', models.CharField(max_length=225, null=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('image_of_product', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('description_of_product', models.TextField(null=True, verbose_name='Descripwtion')),
                ('price_of_product', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('resolution', models.CharField(max_length=215, verbose_name='Resolution')),
                ('accumulator_volume', models.CharField(max_length=235, verbose_name='Volume of acc')),
                ('random_access_memory', models.CharField(max_length=255, verbose_name='RAM')),
                ('videocard', models.CharField(max_length=255, null=True, verbose_name='Videocard')),
                ('back_camera_mp', models.CharField(max_length=255, verbose_name='Back_camera')),
                ('front_camera_mp', models.CharField(max_length=255, verbose_name='Front_camera')),
                ('Product_create_company', models.CharField(max_length=12, null=True, verbose_name='Which_company_produce(Hp,lenovo e.t.c)')),
                ('screen_resolution', models.CharField(max_length=123, verbose_name='Resolution')),
                ('smart_technology_support', models.CharField(max_length=20, verbose_name='Smart_technologies')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='category')),
            ],
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='television',
            name='category',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
        migrations.DeleteModel(
            name='Television',
        ),
    ]
