# Generated by Django 3.2 on 2021-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210510_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='screen_resolution',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=89, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='accumulator_volume',
            field=models.CharField(max_length=235, null=True, verbose_name='Volume of acc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='back_camera_mp',
            field=models.CharField(max_length=255, null=True, verbose_name='Back camera'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_camera_mp',
            field=models.CharField(max_length=255, null=True, verbose_name='Front camera'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(max_length=215, null=True, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='smart_technology_support',
            field=models.CharField(max_length=20, null=True, verbose_name='Smart_technologies'),
        ),
    ]
