# Generated by Django 3.2 on 2021-05-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_random_access_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_create_company',
            field=models.CharField(blank=True, max_length=12, verbose_name='Which_company_produce(Hp,lenovo e.t.c)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='accumulator_volume',
            field=models.CharField(blank=True, max_length=235, verbose_name='Volume of acc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='back_camera_mp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Back camera'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_of_product',
            field=models.TextField(blank=True, verbose_name='Descripwtion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_camera_mp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Front camera'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_of_product',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='random_access_memory',
            field=models.CharField(blank=True, max_length=255, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=215, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='smart_technology_support',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Smart_technologies'),
        ),
        migrations.AlterField(
            model_name='product',
            name='videocard',
            field=models.CharField(blank=True, max_length=255, verbose_name='Videocard'),
        ),
    ]
